#!/usr/bin/env python3
import os

os.makedirs("cache", exist_ok=True)

with open("version", "r", encoding="utf-8") as f:
    ver_str = f.read().strip()

ma, mi, pa = map(int, ver_str.split("."))

# C
with open("cache/version.h", "w") as f:
    f.write(f"""
// Generated by `gen_version.py`
#ifndef PROKA_VERSION_H
#define PROKA_VERSION_H

#define PROKA_VERSION_MAJ {ma}
#define PROKA_VERSION_MIN {mi}
#define PROKA_VERSION_PAT {pa}
#define PROKA_VERSION {{ {ma}, {mi}, {pa} }}

#endif
""")

# ASM
with open("cache/version.inc", "w") as f:
    f.write(f"""
; Generated by `gen_version.py`
%define PROKA_VERSION_MAJ {ma}
%define PROKA_VERSION_MIN {mi}
%define PROKA_VERSION_PAT {pa}
PROKA_VERSION dw {ma}, {mi}, {pa}
""")

# Rust
with open("library/src/version.rs", "w") as f:
    f.write(f"""
// Generated by `gen_version.py`
pub const VERSION: [u16; 3] = [{ma}, {mi}, {pa}];
""")

with open("cache/version.rs", "w") as f:
    f.write(f"""
// Generated by `gen_version.py`
pub const VERSION: [u16; 3] = [{ma}, {mi}, {pa}]; 
""")

with open("uefi/src/version.rs", "w") as f:
    f.write(f"""
// Generated by `gen_version.py`
pub const VERSION: [u16; 3] = [{ma}, {mi}, {pa}]; 
""")


print(f"[INFO] Version {ma}.{mi}.{pa} → cache/")
