[package]
name = "proka_bootloader"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
uefi = "0.35.0"

[features]
default = []
loader_main = []
