[package]
name = "loader"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
uefi = { version = "0.35.0", features = ["global_allocator", "alloc", "panic_handler"] }
library = { path = "../library" }
