# Proka Bootloader - The bootloader of Proka OS
# Copyright (C) RainSTR Studio 2026, All rights reserved.
#
# This is the builder of the Proka Bootloader (legacy), which
# will automatically build the whole legacy boot section to
# one file.

BOOT_IMG := boot.img

NASM := nasm
NASM_FLAGS := -f bin

